name: Publish Nuget Package 

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
      - 'develop'    # Run the workflow when pushing to the develop branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      
      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v1.1.1
        id: gitversion

      - name: Print Version
        run: echo "🎉 Version ${{ steps.gitversion.outputs.SemVer }}"
      
      - name: Create git tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag v${{ steps.gitversion.outputs.SemVer }}
          git push origin v${{ steps.gitversion.outputs.SemVer }}